// MIT License
// Copyright (c) 2020 NedMakesGames
#pragma kernel Main

struct IndirectArgs {
    uint numVerticesPerInstance;
    uint numInstances;
    uint startVertexIndex;
    uint startInstanceIndex;
};
RWStructuredBuffer<IndirectArgs> _IndirectArgsBuffer;

// Multiply the number of vertices by three to convert from triangles
[numthreads(1, 1, 1)]
void Main(uint3 id : SV_DispatchThreadID) {
    _IndirectArgsBuffer[0].numVerticesPerInstance *= 3;
}
